version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - 8081:5000
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    restart: unless-stopped
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres