version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - 8081:5000
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
  redis:
    image: redis
    restart: unless-stopped